- name: Set up Django project in virtual environment
  hosts: all
  become: yes
  tasks:
    - name: Install Python3 and venv package
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
        state: present
        update_cache: yes

    - name: Create a virtual environment
      command:
        cmd: python3 -m venv /mnt/x/notesapp/venv  # Full path to the virtual environment
        creates: /mnt/x/notesapp/venv/bin/activate  # Updated to match Linux virtualenv structure

    - name: Install Python packages in venv from requirements.txt
      pip:
        requirements: /mnt/x/notesapp/requirements.txt
        virtualenv: /mnt/x/notesapp/venv
        virtualenv_python: python3
      when: ansible_facts['distribution'] == "Ubuntu"  # Ensure the task runs only on Ubuntu

    - name: Install additional dependencies in virtual environment
      pip:
        name: "{{ item }}"
        virtualenv: /mnt/x/notesapp/venv
        virtualenv_python: python3
      loop:
        - requests
        - numpy
